* Operating Systems
- Antón López Núñez
- Carlos Martínez Rabuñal

This is a project for the Operating Systems subject in the second year of computer science at Universidad De A Coruña.
All the assignments are in the [[https://github.com/anton2403/SO-shell/tree/main/labAssigments][labAssignments]] folder with descriptions for every function.

The program consists of a shell similar to what bash and zsh do, with some included functions and also the ability to run any other command on the *nix system.

** Basic usage
You can get a list of all the included functions by running the command "*ayuda*", and a small description of each one by running "*ayuda command*" command being the command you are interested in knowing.
You can also run any other command installed in your system like in any other shell as long as the name doesn't conflict with the included commands.
To exit the shell you can run *fin*, *salir*, *bye* or *exit*
** How to run the program
You need to have gcc installed in a *nix operating system like Linux BSD or MacOS
You can compile it with:
#+begin_src make
make
#+end_src
And run it with:
#+begin_src shell
./shell
#+end_src
Or to run it directly:
#+begin_src shell
make run
#+end_src

** What is on each file
Our code is divided into different files to make it easier to work and understand.
*** [[https://github.com/anton2403/SO-shell/blob/main/main.c][main.c]]
Defines structs and data types that are used in the code.
*** [[https://github.com/anton2403/SO-shell/blob/main/list.c][list.c]] and [[https://github.com/anton2403/SO-shell/blob/main/list.h][list.h]]
We opted to use only one implementation of a list to save different kinds of values that are specified on time of creation, you can check the creation of those lists on the main function in [[https://github.com/anton2403/SO-shell/blob/main/main.c][main.c]].